# QA Agent configuration (FastAPI)
project:
  name: "petstore-api"
  type: "fastapi"

app:
  dev:
    base_url: "http://localhost:8765"
    start_command: "uvicorn server:app --reload --port 8765"
    health_endpoint: "/health"

openapi:
  auto_generate: false
  spec_path: "openapi.yaml"

# Test generation defaults
tests:
  output_dir: "tests/qaagent"
  behave:
    enabled: true
    output_dir: "tests/qaagent/behave"
    framework: "behave"
  unit:
    enabled: true
    output_dir: "tests/qaagent/unit"
    framework: "pytest"
  data:
    enabled: true
    output_dir: "tests/qaagent/fixtures"
    format: "json"

exclude:
  paths: []
  tags: []

risk_assessment:
  disable_rules:
    - "health_check_pagination"
  severity_thresholds: {}

llm:
  enabled: false
  provider: "ollama"
  model: "qwen2.5-coder:7b"
  fallback_to_templates: true