"""Utilities for reading evidence generated by Sprint 1 collectors."""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Callable, List, Optional, TypeVar

from qaagent.evidence.models import (
    ChurnRecord,
    CoverageRecord,
    FindingRecord,
    Manifest,
    RecommendationRecord,
    RiskRecord,
)
from qaagent.evidence.run_manager import RunHandle, RunManager

LOGGER = logging.getLogger(__name__)

T = TypeVar("T")


class EvidenceReader:
    """Reads JSONL evidence files for a given run."""

    def __init__(self, run_handle: RunHandle):
        self.handle = run_handle
        self.run_dir = run_handle.run_dir
        self.evidence_dir = run_handle.evidence_dir

    @classmethod
    def from_run_path(cls, run_path: Path, runs_root: Optional[Path] = None) -> "EvidenceReader":
        """Instantiate reader from an existing run directory."""
        manager = RunManager(base_dir=runs_root)
        handle = manager.load_run(run_path)
        return cls(handle)

    def read_findings(self) -> List[FindingRecord]:
        return list(self._read_jsonl("quality.jsonl", _finding_factory))

    def read_coverage(self) -> List[CoverageRecord]:
        return list(self._read_jsonl("coverage.jsonl", _coverage_factory))

    def read_churn(self) -> List[ChurnRecord]:
        return list(self._read_jsonl("churn.jsonl", _churn_factory))

    def read_manifest(self) -> Manifest:
        data = json.loads(self.handle.manifest_path.read_text(encoding="utf-8"))
        return Manifest.from_dict(data)

    def read_risks(self) -> List[RiskRecord]:
        return list(self._read_jsonl("risks.jsonl", _risk_factory))

    def read_recommendations(self) -> List[RecommendationRecord]:
        return list(self._read_jsonl("recommendations.jsonl", _recommendation_factory))

    def _read_jsonl(self, filename: str, factory: Callable[[dict], T]) -> List[T]:
        if not filename:
            return []
        path = self.evidence_dir / filename
        if not path.exists():
            LOGGER.debug("Evidence file missing: %s", path)
            return []

        records: List[T] = []
        with path.open(encoding="utf-8") as fp:
            for line in fp:
                line = line.strip()
                if not line:
                    continue
                try:
                    payload = json.loads(line)
                    records.append(factory(payload))
                except json.JSONDecodeError:
                    LOGGER.warning("Skipping malformed JSON line in %s", path)
                except Exception:  # pragma: no cover - defensive
                    LOGGER.exception("Failed to parse evidence record in %s", path)
        return records


def _finding_factory(data: dict) -> FindingRecord:
    return FindingRecord(
        evidence_id=data.get("evidence_id", ""),
        tool=data.get("tool", ""),
        severity=data.get("severity", ""),
        code=data.get("code"),
        message=data.get("message", ""),
        file=data.get("file"),
        line=data.get("line"),
        column=data.get("column"),
        tags=list(data.get("tags", [])),
        confidence=data.get("confidence"),
        collected_at=data.get("collected_at", ""),
        metadata=dict(data.get("metadata", {})),
    )


def _coverage_factory(data: dict) -> CoverageRecord:
    return CoverageRecord(
        coverage_id=data.get("coverage_id", ""),
        type=data.get("type", "line"),
        component=data.get("component", ""),
        value=float(data.get("value", 0.0)),
        total_statements=data.get("total_statements"),
        covered_statements=data.get("covered_statements"),
        sources=list(data.get("sources", [])),
        linked_cujs=list(data.get("linked_cujs", [])),
        collected_at=data.get("collected_at", ""),
        metadata=dict(data.get("metadata", {})),
    )


def _churn_factory(data: dict) -> ChurnRecord:
    return ChurnRecord(
        evidence_id=data.get("evidence_id", ""),
        path=data.get("path", ""),
        window=data.get("window", ""),
        commits=int(data.get("commits", 0)),
        lines_added=int(data.get("lines_added", 0)),
        lines_deleted=int(data.get("lines_deleted", 0)),
        contributors=int(data.get("contributors", 0)),
        last_commit_at=data.get("last_commit_at"),
        metadata=dict(data.get("metadata", {})),
    )


def _risk_factory(data: dict) -> RiskRecord:
    return RiskRecord.from_dict(data)


def _recommendation_factory(data: dict) -> RecommendationRecord:
    return RecommendationRecord.from_dict(data)
