import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

interface ReportMetadata {
  title: string;
  runId: string;
  createdAt: string;
  targetName: string;
}

interface ReportData {
  metadata: ReportMetadata;
  summary: {
    totalRuns: number;
    highRisks: number;
    avgCoverage: number;
    safeComponents: number;
  };
  topRisks: Array<{
    component: string;
    score: number;
    band: string;
    title: string;
    severity?: string;
  }>;
  coverageGaps?: Array<{
    component: string;
    coverage: number;
  }>;
}

/**
 * Generate Executive Summary PDF (1 page)
 */
export function generateExecutiveSummary(data: ReportData): void {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(20);
  doc.text("QA Agent - Executive Summary", 14, 20);

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Run: ${data.metadata.runId}`, 14, 30);
  doc.text(`Target: ${data.metadata.targetName}`, 14, 35);
  doc.text(`Generated: ${new Date(data.metadata.createdAt).toLocaleDateString()}`, 14, 40);

  doc.setTextColor(0);

  // Summary Metrics
  doc.setFontSize(14);
  doc.text("Key Metrics", 14, 50);

  const metrics = [
    ["Total Runs", data.summary.totalRuns.toString()],
    ["High Risk Components", data.summary.highRisks.toString()],
    ["Average Coverage", `${data.summary.avgCoverage}%`],
    ["Safe Components", data.summary.safeComponents.toString()],
  ];

  autoTable(doc, {
    startY: 55,
    head: [["Metric", "Value"]],
    body: metrics,
    theme: "grid",
    headStyles: { fillColor: [71, 85, 105] }, // slate-600
  });

  // Top Risks
  const finalY = (doc as any).lastAutoTable.finalY || 100;
  doc.setFontSize(14);
  doc.text("Top Risks", 14, finalY + 10);

  const riskRows = data.topRisks.slice(0, 5).map(risk => [
    risk.component,
    risk.score.toFixed(1),
    risk.band,
    risk.title,
  ]);

  autoTable(doc, {
    startY: finalY + 15,
    head: [["Component", "Score", "Band", "Title"]],
    body: riskRows,
    theme: "grid",
    headStyles: { fillColor: [71, 85, 105] },
    columnStyles: {
      1: { cellWidth: 20 },
      2: { cellWidth: 15 },
    },
  });

  // Footer
  const pageCount = (doc.internal as any).getNumberOfPages();
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text(
    `Generated by QA Agent - Page ${pageCount}`,
    14,
    doc.internal.pageSize.height - 10
  );

  // Download
  doc.save(`qa-agent-executive-summary-${data.metadata.runId}.pdf`);
}

/**
 * Generate Technical Report PDF (multi-page, detailed)
 */
export function generateTechnicalReport(data: ReportData): void {
  const doc = new jsPDF();

  // Title Page
  doc.setFontSize(24);
  doc.text("QA Agent", 14, 40);
  doc.setFontSize(18);
  doc.text("Technical Analysis Report", 14, 50);

  doc.setFontSize(12);
  doc.text(`Run ID: ${data.metadata.runId}`, 14, 70);
  doc.text(`Target: ${data.metadata.targetName}`, 14, 77);
  doc.text(`Date: ${new Date(data.metadata.createdAt).toLocaleDateString()}`, 14, 84);

  // Page 2: Summary Metrics
  doc.addPage();
  doc.setFontSize(16);
  doc.text("1. Summary Metrics", 14, 20);

  const summaryData = [
    ["Total Analysis Runs", data.summary.totalRuns.toString()],
    ["High Risk Components (P0/P1)", data.summary.highRisks.toString()],
    ["Average Test Coverage", `${data.summary.avgCoverage}%`],
    ["Safe Components (P2/P3)", data.summary.safeComponents.toString()],
  ];

  autoTable(doc, {
    startY: 30,
    head: [["Metric", "Value"]],
    body: summaryData,
    theme: "striped",
    headStyles: { fillColor: [71, 85, 105] },
  });

  // Page 3: Risk Analysis
  doc.addPage();
  doc.setFontSize(16);
  doc.text("2. Risk Analysis", 14, 20);

  doc.setFontSize(12);
  doc.text("All risks identified in this analysis:", 14, 30);

  const allRiskRows = data.topRisks.map(risk => [
    risk.component,
    risk.score.toFixed(1),
    risk.band,
    risk.severity || "N/A",
    risk.title,
  ]);

  autoTable(doc, {
    startY: 35,
    head: [["Component", "Score", "Band", "Severity", "Description"]],
    body: allRiskRows,
    theme: "striped",
    headStyles: { fillColor: [71, 85, 105] },
    columnStyles: {
      0: { cellWidth: 40 },
      1: { cellWidth: 20 },
      2: { cellWidth: 15 },
      3: { cellWidth: 20 },
    },
  });

  // Page 4: Coverage Gaps (if data available)
  if (data.coverageGaps && data.coverageGaps.length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.text("3. Coverage Gaps", 14, 20);

    doc.setFontSize(12);
    doc.text("Components with coverage below target (80%):", 14, 30);

    const coverageRows = data.coverageGaps.map(gap => [
      gap.component,
      `${Math.round(gap.coverage * 100)}%`,
      `${Math.round((0.8 - gap.coverage) * 100)}%`,
    ]);

    autoTable(doc, {
      startY: 35,
      head: [["Component", "Current Coverage", "Gap to Target"]],
      body: coverageRows,
      theme: "striped",
      headStyles: { fillColor: [71, 85, 105] },
    });
  }

  // Footer on all pages
  const pageCount = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(
      `QA Agent Technical Report - Page ${i} of ${pageCount}`,
      14,
      doc.internal.pageSize.height - 10
    );
  }

  // Download
  doc.save(`qa-agent-technical-report-${data.metadata.runId}.pdf`);
}

/**
 * Generate Trends Report PDF
 */
export function generateTrendsReport(trendsData: any[]): void {
  const doc = new jsPDF();

  // Title
  doc.setFontSize(20);
  doc.text("QA Agent - Trends Report", 14, 20);

  doc.setFontSize(10);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 14, 30);

  // Trend summary table
  doc.setFontSize(14);
  doc.text("Quality Trends Over Time", 14, 40);

  const trendRows = trendsData.map(point => [
    point.run_id,
    new Date(point.created_at).toLocaleDateString(),
    point.average_coverage ? `${Math.round(point.average_coverage * 100)}%` : "N/A",
    point.high_risk_count?.toString() || "0",
    point.average_risk_score?.toFixed(1) || "N/A",
  ]);

  autoTable(doc, {
    startY: 45,
    head: [["Run ID", "Date", "Avg Coverage", "High Risks", "Avg Risk Score"]],
    body: trendRows,
    theme: "grid",
    headStyles: { fillColor: [71, 85, 105] },
  });

  doc.save(`qa-agent-trends-${new Date().toISOString().split('T')[0]}.pdf`);
}
